[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "new-project"
version = "0.1.2"
description = "New Python project"
authors = [{name = "Bosko"}]
requires-python = ">=3.8"
license = { text = "MIT" }
dependencies = [
    "pytest",
    "pytest-cov",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
